import CryptoKit
import Foundation

// Wire protocol, version 1.
//
// Two endpoints, POST /retrieve and POST /config. Request and response bodies
// are each a single ChaCha20-Poly1305 message in CryptoKit's combined form:
// 12-byte nonce, ciphertext, 16-byte tag. The key is 32 random bytes shared
// with the plugin.
//
//   request plaintext:   {"ts": <unix seconds>, "id": "<random>"}
//   response plaintext:  {"id": "<echoed>", "seq": <number>, "data": …}
//
//   /retrieve data:  {"<source>": {"error": "…", "data": <value>}, …}
//   /config data:    {"<source>": <JSON Schema of that source's data>, …}
//
// Each source has its own `error`, empty when there was no problem getting
// its value. `seq` identifies the config; when it differs from the one the
// plugin holds, the plugin reads /config again. A request that is refused
// gets an HTTP error status instead.
//
// The associated data names the protocol version, the direction and the
// path, so a message cannot be replayed in the other direction or against
// the other endpoint. Nonces are always generated by CryptoKit.
enum Wire {
    static let retrievePath = "/retrieve"
    static let configPath = "/config"
    static let paths = [retrievePath, configPath]
    static let maxSkew: TimeInterval = 60   // how far a request's timestamp may be from now
    static let maxIDLength = 64

    static func requestContext(_ path: String) -> Data { Data("retriever/1 request \(path)".utf8) }
    static func responseContext(_ path: String) -> Data { Data("retriever/1 response \(path)".utf8) }

    enum Failure: Error, Equatable {
        case unauthenticated   // not sealed with our key for this endpoint and direction
        case malformed         // authentic, but not a request
        case stale             // authentic, but its timestamp is too far from now
    }

    struct Request: Codable {
        let ts: Int
        let id: String
    }

    struct Response<Values: Codable>: Codable {
        let id: String
        let seq: UInt32
        let data: Values
    }

    static func key(base64: String) -> SymmetricKey? {
        guard let data = Data(base64Encoded: base64), data.count == 32 else { return nil }
        return SymmetricKey(data: data)
    }

    /// Returns the request ID to echo, or throws the reason the request is refused.
    static func open(request body: Data, path: String, key: SymmetricKey, now: Date = Date()) throws -> String {
        guard let box = try? ChaChaPoly.SealedBox(combined: body),
              let plain = try? ChaChaPoly.open(box, using: key, authenticating: requestContext(path))
        else { throw Failure.unauthenticated }
        guard let request = try? JSONDecoder().decode(Request.self, from: plain),
              !request.id.isEmpty, request.id.count <= maxIDLength
        else { throw Failure.malformed }
        guard abs(now.timeIntervalSince1970 - Double(request.ts)) <= maxSkew else { throw Failure.stale }
        return request.id
    }

    static func seal<Values: Codable>(response values: Values, id: String, seq: UInt32, path: String, key: SymmetricKey) throws -> Data {
        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .iso8601
        let plain = try encoder.encode(Response(id: id, seq: seq, data: values))
        return try ChaChaPoly.seal(plain, using: key, authenticating: responseContext(path)).combined
    }
}
