import CryptoKit
import Foundation

// Wire protocol, version 1.
//
// Three endpoints, POST /server, POST /config and POST /retrieve. Request and
// response bodies are each a single ChaCha20-Poly1305 message in CryptoKit's
// combined form: 12-byte nonce, ciphertext, 16-byte tag. The key is 32
// random bytes shared with the plugin.
//
//   request plaintext:   {"ts": <unix seconds>, "id": "<random>", "protocol": <number, optional>}
//   response plaintext:  {"id": "<echoed>", "seq": <number>, "data": …}
//
//   /server data:    {"name", "version", "protocol": {"min", "max"}, …}
//   /config data:    {"<source>": <JSON Schema of that source's data>, …}
//   /retrieve data:  {"<source>": {"error": "…", "data": <value>}, …}
//
// /server says which protocols this server speaks, as an inclusive range. A
// client picks one and names it in its /config and /retrieve requests; a
// request that names none is taken to be protocol 1. /server itself takes
// no protocol: it has to be answerable before one is chosen.
//
// Each source has its own `error`, empty when there was no problem getting
// its value. `seq` identifies the config; when it differs from the one the
// plugin holds, the plugin reads /config again.
//
// A request that does not decrypt gets no response at all: the connection is
// closed, and so is one for an unknown path, a method other than POST, or
// malformed HTTP. Nothing is said to anyone who has not shown the key. A
// request that does decrypt but is refused gets an HTTP error status that
// says why.
//
// The associated data names the envelope ("retriever/1", which is fixed and
// is not the negotiated protocol), the direction and the path, so a message
// cannot be replayed in the other direction or against another endpoint.
// Nor can a request be replayed as itself: the server answers each ID once
// (see AnsweredRequests), and gives a repeat no response.
// Nonces are always generated by CryptoKit.
enum Wire {
    static let serverPath = "/server"
    static let configPath = "/config"
    static let retrievePath = "/retrieve"
    static let paths = [serverPath, configPath, retrievePath]

    /// Names the plugin keeps for values of its own, beside the sources': the
    /// reason a fetch failed, and what /server said. A plugin refuses a
    /// server that names a source either.
    static let reservedSourceNames = ["error", "server"]

    /// The protocols this server speaks, and the one a request means when it names none.
    static let protocols = 1...1
    static let defaultProtocol = 1
    static let maxSkew: TimeInterval = 60   // how far a request's timestamp may be from now
    static let maxIDLength = 64

    static func requestContext(_ path: String) -> Data { Data("retriever/1 request \(path)".utf8) }
    static func responseContext(_ path: String) -> Data { Data("retriever/1 response \(path)".utf8) }

    enum Failure: Error, Equatable {
        case unauthenticated   // not sealed with our key for this endpoint and direction
        case malformed         // authentic, but not a request
        case stale             // authentic, but its timestamp is too far from now
        case unsupportedProtocol   // authentic, but asks for a protocol outside `protocols`

        /// The status to answer with, or nil to close the connection
        /// without answering. Only a request that decrypted is told anything.
        var status: String? {
            switch self {
            case .unauthenticated: return nil
            case .malformed: return "400 Bad Request"
            // Said distinctly so that clock skew is not mistaken for a wrong key.
            case .stale: return "400 Stale Timestamp"
            case .unsupportedProtocol: return "400 Unsupported Protocol"
            }
        }
    }

    struct Request: Codable {
        let ts: Int
        let id: String
        var `protocol`: Int?
    }

    /// A request that was accepted: the ID to echo and the protocol to answer in.
    struct Accepted: Equatable {
        let id: String
        let `protocol`: Int
    }

    struct Response<Values: Codable>: Codable {
        let id: String
        let seq: UInt32
        let data: Values
    }

    static func key(base64: String) -> SymmetricKey? {
        guard let data = Data(base64Encoded: base64), data.count == 32 else { return nil }
        return SymmetricKey(data: data)
    }

    /// Returns the accepted request, or throws the reason it is refused.
    static func open(request body: Data, path: String, key: SymmetricKey, now: Date = Date()) throws -> Accepted {
        guard let box = try? ChaChaPoly.SealedBox(combined: body),
              let plain = try? ChaChaPoly.open(box, using: key, authenticating: requestContext(path))
        else { throw Failure.unauthenticated }
        guard let request = try? JSONDecoder().decode(Request.self, from: plain),
              !request.id.isEmpty, request.id.count <= maxIDLength
        else { throw Failure.malformed }
        guard abs(now.timeIntervalSince1970 - Double(request.ts)) <= maxSkew else { throw Failure.stale }
        if path == serverPath { return Accepted(id: request.id, protocol: defaultProtocol) }
        let requested = request.protocol ?? defaultProtocol
        guard protocols.contains(requested) else { throw Failure.unsupportedProtocol }
        return Accepted(id: request.id, protocol: requested)
    }

    static func seal<Values: Codable>(response values: Values, id: String, seq: UInt32, path: String, key: SymmetricKey) throws -> Data {
        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .iso8601
        let plain = try encoder.encode(Response(id: id, seq: seq, data: values))
        return try ChaChaPoly.seal(plain, using: key, authenticating: responseContext(path)).combined
    }
}
