import CryptoKit
import Foundation

// Wire protocol, version 1.
//
// Three endpoints, POST /server, POST /config and POST /retrieve. Request and
// response bodies are each a single ChaCha20-Poly1305 message in CryptoKit's
// combined form: 12-byte nonce, ciphertext, 16-byte tag. The key is 32
// random bytes shared with the plugin.
//
//   request plaintext:   {"ts": <unix seconds>, "id": "<random>", "protocol": <number, optional>}
//   response plaintext:  {"id": "<echoed>", "seq": <number>, "data": …}
//
//   /server data:    {"name", "version", "protocol": {"min", "max"}, …}
//   /config data:    {"<source>": <JSON Schema of that source's data>, …}
//   /retrieve data:  {"<source>": {"error": "…", "data": <value>}, …}
//
// /server says which protocols this server speaks, as an inclusive range. A
// client picks one and names it in its /config and /retrieve requests; a
// request that names none is taken to be protocol 1. /server itself takes
// no protocol: it has to be answerable before one is chosen.
//
// Each source has its own `error`, empty when there was no problem getting
// its value. `seq` identifies the config; when it differs from the one the
// plugin holds, the plugin reads /config again.
//
// A request that does not decrypt gets no response at all: the connection is
// closed, and so is one for an unknown path, a method other than POST, or
// malformed HTTP. Nothing is said to anyone who has not shown the key. A
// request that does decrypt but is refused gets an HTTP error status that
// says why.
//
// The associated data names the envelope ("retriever/1", which is fixed and
// is not the negotiated protocol), the direction and the path, so a message
// cannot be replayed in the other direction or against another endpoint.
// Nor can a request be replayed as itself: the server answers each ID once
// (see AnsweredRequests), and gives a repeat no response.
// Nonces are always generated by CryptoKit.
enum Wire {
    static let serverInfoPath = "/server"
    static let configPath = "/config"
    static let retrievePath = "/retrieve"
    static let endpointPaths = [serverInfoPath, configPath, retrievePath]

    /// Names the plugin keeps for values of its own, beside the sources': the
    /// reason a fetch failed, and what /server said. A plugin refuses a
    /// server that names a source either.
    static let reservedSourceNames = ["error", "server"]

    /// The protocols this server speaks, and the one a request means when it names none.
    static let protocolVersions = 1...1
    static let defaultProtocolVersion = 1
    static let maxClockDifference: TimeInterval = 60   // how far a request's timestamp may be from now
    static let maxRequestIDLength = 64

    /// What a request to an endpoint is authenticated with, beside its own contents.
    static func requestAuthenticatedData(_ path: String) -> Data { Data("retriever/1 request \(path)".utf8) }
    /// What a response from an endpoint is authenticated with.
    static func responseAuthenticatedData(_ path: String) -> Data { Data("retriever/1 response \(path)".utf8) }

    /// Why a request is not served.
    enum Failure: Error, Equatable {
        case unauthenticated   // not sealed with our key for this endpoint and direction
        case malformed         // authentic, but not a request
        case stale             // authentic, but its timestamp is too far from now
        case unsupportedProtocol   // authentic, but asks for a protocol outside `protocolVersions`

        /// The status to answer with, or nil to close the connection
        /// without answering. Only a request that decrypted is told anything.
        var status: String? {
            switch self {
            case .unauthenticated: return nil
            case .malformed: return "400 Bad Request"
            // Said distinctly so that clock skew is not mistaken for a wrong key.
            case .stale: return "400 Stale Timestamp"
            case .unsupportedProtocol: return "400 Unsupported Protocol"
            }
        }
    }

    /// A request's plaintext. The names on the wire are short; these are not.
    struct Request: Codable {
        let timestamp: Int   // seconds since 1970, by the sender's clock
        let id: String
        var protocolVersion: Int?

        enum CodingKeys: String, CodingKey {
            case timestamp = "ts", id, protocolVersion = "protocol"
        }
    }

    /// A request that was accepted: the ID to echo and the protocol version to answer in.
    struct Accepted: Equatable {
        let id: String
        let protocolVersion: Int
    }

    /// A response's plaintext.
    struct Response<Values: Codable>: Codable {
        let id: String
        let sequenceNumber: UInt32
        let data: Values

        enum CodingKeys: String, CodingKey {
            case id, sequenceNumber = "seq", data
        }
    }

    /// The transport key that `base64` encodes, or nil if it is not the base64 of exactly 32 bytes.
    static func transportKey(base64: String) -> SymmetricKey? {
        guard let data = Data(base64Encoded: base64), data.count == 32 else { return nil }
        return SymmetricKey(data: data)
    }

    /// Returns the accepted request, or throws the reason it is refused.
    static func open(request body: Data, path: String, key: SymmetricKey, now: Date = Date()) throws -> Accepted {
        guard let box = try? ChaChaPoly.SealedBox(combined: body),
              let plain = try? ChaChaPoly.open(box, using: key, authenticating: requestAuthenticatedData(path))
        else { throw Failure.unauthenticated }
        guard let request = try? JSONDecoder().decode(Request.self, from: plain),
              !request.id.isEmpty, request.id.count <= maxRequestIDLength
        else { throw Failure.malformed }
        guard abs(now.timeIntervalSince1970 - Double(request.timestamp)) <= maxClockDifference else { throw Failure.stale }
        if path == serverInfoPath { return Accepted(id: request.id, protocolVersion: defaultProtocolVersion) }
        let requested = request.protocolVersion ?? defaultProtocolVersion
        guard protocolVersions.contains(requested) else { throw Failure.unsupportedProtocol }
        return Accepted(id: request.id, protocolVersion: requested)
    }

    /// Seals a response for one endpoint.
    /// - Parameters:
    ///   - id: the request's ID, echoed so the plugin knows whose answer this is.
    ///   - sequenceNumber: identifies the config the plugin should be holding.
    /// - Throws: if `values` cannot be written as JSON.
    static func seal<Values: Codable>(response values: Values, id: String, sequenceNumber: UInt32, path: String, key: SymmetricKey) throws -> Data {
        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .iso8601
        let plain = try encoder.encode(Response(id: id, sequenceNumber: sequenceNumber, data: values))
        return try ChaChaPoly.seal(plain, using: key, authenticating: responseAuthenticatedData(path)).combined
    }
}
